[DAGSHUB]
USERNAME = "MohammoD2"
TOKEN = "5cd659763bb8e53abe56bf659b527afffe0e7935"

[GDRIVE_KEYS]
SCALER_KEY = "1-h22rcLSweKyrhAhxLvPvv_ToMfq15c8"
ENCODER_KEY = "1-RvY487pU5uoN-DvmzSgnjsW4sGBHZ1M"
KMEANS_KEY = "1Bld4Yp4c5CmqkgFkEFgEJNODAZQ8r07E"
MODEL_KEY = "1Yz9VZbEDgpQdKe8NuBJ2QhRb41b_mKbE"
TEST_CSV = "1LTRQ9_FQh8J3RG72EWv-fXOkqvwqoTPp"
PLOT_DATA = "11SmdqCXjjbKyvDiQ8rpwycpHn1tRjhGd"
